version: '3'

services:
  rds:
    image: postgres:11.11-alpine # matched Huawei version. ## event test
    ports:
      - 54322:5432
    environment:
      - POSTGRES_USER=tester
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db