name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm i -g npm
      - run: npm ci
      - run: ./npm_release.sh packages/core
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: ./npm_release.sh packages/mikroorm
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: ./npm_release.sh packages/lambda
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
